# Generated by Django 3.2.5 on 2022-11-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_first', models.CharField(max_length=100)),
                ('employee_last', models.CharField(max_length=100)),
                ('employee_shift', models.CharField(max_length=100)),
            ],
        ),
    ]
