# Generated by Django 3.2.5 on 2022-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jjfdsj',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
