# Generated by Django 3.2.5 on 2022-11-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221124_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='senority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
